In [42]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [43]:
df=pd.read_csv("C:/Users/ramya/Downloads/healthcare_dataset.csv.zip")
print("Dataset loaded successfully!")

Dataset loaded successfully!

In [44]:
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [45]:
df.tail()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [46]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 55500
Number of columns: 15

In [47]:
print("Column Names:")
print(df.columns.tolist())

Column Names:
['Name', 'Age', 'Gender', 'Blood Type', 'Medical Condition', 'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider', 'Billing Amount', 'Room Number', 'Admission Type', 'Discharge Date', 'Medication', 'Test Results']

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB

In [49]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [50]:
print("Number of duplicate rows:", df.duplicated().sum())

Number of duplicate rows: 534

In [51]:
df = df.drop_duplicates()

print("Duplicates removed.")
print("Current dataset shape:", df.shape)

Duplicates removed.
Current dataset shape: (54966, 15)

In [52]:
df.columns = (
    df.columns
    .str.strip()
    .str.replace(" ", "_")
)

print(df.columns.tolist())

['Name', 'Age', 'Gender', 'Blood_Type', 'Medical_Condition', 'Date_of_Admission', 'Doctor', 'Hospital', 'Insurance_Provider', 'Billing_Amount', 'Room_Number', 'Admission_Type', 'Discharge_Date', 'Medication', 'Test_Results']

In [53]:
df["Date_of_Admission"] = pd.to_datetime(
    df["Date_of_Admission"],
    errors="coerce"
)

df["Discharge_Date"] = pd.to_datetime(
    df["Discharge_Date"],
    errors="coerce"
)

print(df[["Date_of_Admission", "Discharge_Date"]].dtypes)

Date_of_Admission    datetime64[ns]
Discharge_Date       datetime64[ns]
dtype: object

In [54]:
print(df[["Age", "Billing_Amount", "Room_Number"]].describe())

                Age  Billing_Amount   Room_Number
count  54966.000000    54966.000000  54966.000000
mean      51.535185    25544.306284    301.124404
std       19.605661    14208.409711    115.223143
min       13.000000    -2008.492140    101.000000
25%       35.000000    13243.718641    202.000000
50%       52.000000    25542.749145    302.000000
75%       68.000000    37819.858159    401.000000
max       89.000000    52764.276736    500.000000

In [55]:
# Check negative billing amounts
negative_billing = (df["Billing_Amount"] < 0).sum()

print("Number of negative billing amounts:", negative_billing)

Number of negative billing amounts: 106

In [56]:
negative_bills = df[df["Billing_Amount"] < 0]

print("Negative billing records:")
print(negative_bills[[
    "Name",
    "Age",
    "Medical_Condition",
    "Billing_Amount",
    "Admission_Type"
]].head(20))

Negative billing records:
                           Name  Age Medical_Condition  Billing_Amount  \
132             ashLEy ERIcKSoN   32            Cancer     -502.507813
799           CHRisTOPHer wEiss   49            Asthma    -1018.245371
1018              AsHley WaRnER   60      Hypertension     -306.364925
1421               JAY galloWaY   74            Asthma     -109.097122
2103          josHUa wilLIamSon   72          Diabetes     -576.727907
2696              Scott VaZqUEz   74          Diabetes     -135.986000
2855             CaROl aNDErSoN   39      Hypertension     -370.983674
3772   mr. ChRIStOPhER aLvARaDO   77           Obesity    -1310.272895
5445             ALExAndrA KHaN   32         Arthritis     -692.408820
5708                 JosEPh cOx   23          Diabetes     -353.865186
6336         miTchElL MAlDOnADo   41            Asthma     -378.960784
6596            juLiE cHRisTIAn   28          Diabetes     -367.203959
6798          AlExaNDER gArdneR   45            Cancer     -198.283806
6961               anGelA aLlEn   83          Diabetes      -43.098522
8757                 ALAN scOTT   48            Asthma     -857.125933
10245              branDOn Hall   27      Hypertension     -155.082020
10516            LUCAS SuLLIvan   31           Obesity     -211.723845
10736             REbecCa ClinE   39            Asthma     -656.153072
10768             vaLERIe ALlEn   82          Diabetes     -227.995064
12074               BRiAN YOuNg   85            Cancer     -147.072199

      Admission_Type
132           Urgent
799         Elective
1018        Elective
1421       Emergency
2103          Urgent
2696        Elective
2855        Elective
3772        Elective
5445        Elective
5708        Elective
6336          Urgent
6596          Urgent
6798        Elective
6961          Urgent
8757          Urgent
10245         Urgent
10516      Emergency
10736      Emergency
10768         Urgent
12074      Emergency

In [59]:
df = df[df["Billing_Amount"] >= 0].copy()

print("Negative billing records removed.")
print("Current dataset shape:", df.shape)

Negative billing records removed.
Current dataset shape: (54860, 15)

In [62]:
print("Negative Age values:", (df["Age"] < 0).sum())
print("Negative Room Number values:", (df["Room_Number"] < 0).sum())
print("Negative Length of Stay:", (df["Length_of_Stay"] < 0).sum())

Negative Age values: 0
Negative Room Number values: 0
Negative Length of Stay: 0

In [61]:
df["Length_of_Stay"] = (
    df["Discharge_Date"] - df["Date_of_Admission"]
).dt.days

df[[
    "Date_of_Admission",
    "Discharge_Date",
    "Length_of_Stay"
]].head()

  Date_of_Admission Discharge_Date  Length_of_Stay
0        2024-01-31     2024-02-02               2
1        2019-08-20     2019-08-26               6
2        2022-09-22     2022-10-07              15
3        2020-11-18     2020-12-18              30
4        2022-09-19     2022-10-09              20

In [63]:
print(
    "Invalid Length of Stay:",
    (df["Length_of_Stay"] < 0).sum()
)

Invalid Length of Stay: 0

In [64]:
df["Age_Group"] = pd.cut(
    df["Age"],
    bins=[0, 18, 30, 45, 60, 75, 100],
    labels=[
        "0-18",
        "19-30",
        "31-45",
        "46-60",
        "61-75",
        "76-100"
    ]
)

df[["Age", "Age_Group"]].head()

   Age Age_Group
0   30     19-30
1   62     61-75
2   76    76-100
3   28     19-30
4   43     31-45

In [65]:
print("Gender:")
print(df["Gender"].value_counts())

print("\nMedical Conditions:")
print(df["Medical_Condition"].value_counts())

print("\nAdmission Types:")
print(df["Admission_Type"].value_counts())

print("\nTest Results:")
print(df["Test_Results"].value_counts())

Gender:
Gender
Male      27449
Female    27411
Name: count, dtype: int64

Medical Conditions:
Medical_Condition
Arthritis       9207
Diabetes        9197
Hypertension    9131
Obesity         9127
Cancer          9121
Asthma          9077
Name: count, dtype: int64

Admission Types:
Admission_Type
Elective     18437
Urgent       18353
Emergency    18070
Name: count, dtype: int64

Test Results:
Test_Results
Abnormal        18399
Normal          18302
Inconclusive    18159
Name: count, dtype: int64

In [66]:
df["Name"] = df["Name"].str.title()

print(df["Name"].head(10))

0         Bobby Jackson
1          Leslie Terry
2           Danny Smith
3          Andrew Watts
4         Adrienne Bell
5         Emily Johnson
6        Edward Edwards
7    Christina Martinez
8       Jasmine Aguilar
9      Christopher Berg
Name: Name, dtype: object

In [67]:
text_columns = [
    "Gender",
    "Blood_Type",
    "Medical_Condition",
    "Admission_Type",
    "Test_Results"
]

for col in text_columns:
    df[col] = df[col].str.title()

print(df[text_columns].head())

   Gender Blood_Type Medical_Condition Admission_Type  Test_Results
0    Male         B-            Cancer         Urgent        Normal
1    Male         A+           Obesity      Emergency  Inconclusive
2  Female         A-           Obesity      Emergency        Normal
3  Female         O+          Diabetes       Elective      Abnormal
4  Female        Ab+            Cancer         Urgent      Abnormal

In [68]:
print("Admission date range:")
print(df["Date_of_Admission"].min(), "to", df["Date_of_Admission"].max())

print("\nDischarge date range:")
print(df["Discharge_Date"].min(), "to", df["Discharge_Date"].max())

Admission date range:
2019-05-08 00:00:00 to 2024-05-07 00:00:00

Discharge date range:
2019-05-09 00:00:00 to 2024-06-06 00:00:00

In [69]:
print("Final dataset shape:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

Final dataset shape: (54860, 17)

Column names:
['Name', 'Age', 'Gender', 'Blood_Type', 'Medical_Condition', 'Date_of_Admission', 'Doctor', 'Hospital', 'Insurance_Provider', 'Billing_Amount', 'Room_Number', 'Admission_Type', 'Discharge_Date', 'Medication', 'Test_Results', 'Length_of_Stay', 'Age_Group']

Data types:
Name                          object
Age                            int64
Gender                        object
Blood_Type                    object
Medical_Condition             object
Date_of_Admission     datetime64[ns]
Doctor                        object
Hospital                      object
Insurance_Provider            object
Billing_Amount               float64
Room_Number                    int64
Admission_Type                object
Discharge_Date        datetime64[ns]
Medication                    object
Test_Results                  object
Length_of_Stay                 int64
Age_Group                   category
dtype: object

In [70]:
print("Missing values after preprocessing:")
print(df.isnull().sum())

Missing values after preprocessing:
Name                  0
Age                   0
Gender                0
Blood_Type            0
Medical_Condition     0
Date_of_Admission     0
Doctor                0
Hospital              0
Insurance_Provider    0
Billing_Amount        0
Room_Number           0
Admission_Type        0
Discharge_Date        0
Medication            0
Test_Results          0
Length_of_Stay        0
Age_Group             0
dtype: int64

In [71]:
df.head()

,Name,Age,Gender,Blood_Type,Medical_Condition,Date_of_Admission,Doctor,Hospital,Insurance_Provider,Billing_Amount,Room_Number,Admission_Type,Discharge_Date,Medication,Test_Results,Length_of_Stay,Age_Group
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal,2,19-30
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,6,61-75
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal,15,76-100
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal,30,19-30
4,Adrienne Bell,43,Female,Ab+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal,20,31-45

In [73]:
output_path = "C:/Users/ramya/Downloads/healthcare_cleaned.csv"

df.to_csv(output_path, index=False)

print("Final cleaned dataset saved successfully!")
print("File:", output_path)
print("Rows:", len(df))
print("Columns:", len(df.columns))

Final cleaned dataset saved successfully!
File: C:/Users/ramya/Downloads/healthcare_cleaned.csv
Rows: 54860
Columns: 17